{
 "title": "Diabetes Prediction ML System Monitoring",
 "tags": [
  "mlops",
  "prometheus",
  "fastapi",
  "dicoding"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Prediction Response Latency p95 (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=\"/predict\"}[1m])) by (le))",
     "legendFormat": "p95 Latency"
    }
   ]
  },
  {
   "title": "HTTP Response Status Codes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (status)",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Total Prediction Requests Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler=\"/predict\"})",
     "legendFormat": "Total Predict Inferences"
    }
   ]
  }
 ]
}